[package]
name = "cloudillo-meta-adapter-sqlite"
version = "0.8.6"
edition = "2021"

[dependencies]
async-trait = "0.1.89"
cloudillo = { path = "../../server" }
libsqlite3-sys = { version = "0.30.1", features = ["bundled"] }
serde_json = "1.0.149"
sqlx = { version = "0.8.6", features = ["sqlite", "runtime-tokio-rustls"] }
tokio = { version = "1.49.0", features = ["fs"] }

[dev-dependencies]
tempfile = "3.24"
tokio = { version = "1.49.0", features = ["rt"] }
